// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DogamiExists(arg1) {
  return window['go']['main']['DogamiService']['DogamiExists'](arg1);
}

export function DownloadAllDogamis() {
  return window['go']['main']['DogamiService']['DownloadAllDogamis']();
}

export function FindAllDogamis() {
  return window['go']['main']['DogamiService']['FindAllDogamis']();
}

export function FindDogami(arg1) {
  return window['go']['main']['DogamiService']['FindDogami'](arg1);
}

export function GetDogami(arg1) {
  return window['go']['main']['DogamiService']['GetDogami'](arg1);
}

export function SaveDogami(arg1, arg2) {
  return window['go']['main']['DogamiService']['SaveDogami'](arg1, arg2);
}

export function SearchDogami(arg1) {
  return window['go']['main']['DogamiService']['SearchDogami'](arg1);
}

export function UpdateDogami(arg1) {
  return window['go']['main']['DogamiService']['UpdateDogami'](arg1);
}
