// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DogamiExists(arg1:number):Promise<boolean>;

export function DownloadAllDogamis():Promise<void>;

export function FindAllDogamis():Promise<Array<main.Dogami>>;

export function FindDogami(arg1:number):Promise<main.Dogami>;

export function GetDogami(arg1:number):Promise<main.Dogami>;

export function SaveDogami(arg1:main.Dogami,arg2:boolean):Promise<void>;

export function SearchDogami(arg1:string):Promise<Array<main.Dogami>>;

export function UpdateDogami(arg1:number):Promise<main.Dogami>;
